# Generated by Django 4.1.1 on 2022-09-21 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='vis',
            field=models.BooleanField(default=True),
        ),
    ]
