# Generated by Django 4.1.1 on 2022-09-29 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_member_address'),
        ('blog', '0002_blog_vis'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='member',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.member'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='blog',
            table='blog',
        ),
    ]
