# Generated by Django 4.1.1 on 2022-09-23 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='login_id',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
