# Generated by Django 4.1.1 on 2022-09-23 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_member_login_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='login_id',
            field=models.CharField(blank=True, max_length=256, unique=True),
        ),
    ]
