# Generated by Django 4.1.1 on 2022-09-26 06:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_member_login_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='member',
            name='login_id',
            field=models.CharField(blank=True, max_length=256, unique=True),
        ),
    ]
