# Generated by Django 4.1.1 on 2022-09-26 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_member_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
