# Generated by Django 4.1.1 on 2022-09-26 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_member_create_date'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='member',
            table='member',
        ),
    ]
