# Generated by Django 4.1.1 on 2022-09-27 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_member_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='address',
            field=models.IntegerField(default=23444, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='login_id',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
