# Generated by Django 4.1.1 on 2022-09-27 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_member_address_alter_member_login_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
