# Generated by Django 4.1.1 on 2022-09-27 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_member_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='address',
            field=models.IntegerField(),
        ),
    ]
